inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/RedundantConstantBase:
  Exclude:
    - config/environments/*.rb

Naming/MethodParameterName:
  Exclude:
    - app/views/**/*.rb
    - test/components/**/*.rb

Lint/MissingSuper:
  Exclude:
    - app/views/**/*.rb
    - app/queries/**/*.rb

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/initializers/devise.rb
    - config/routes.rb
    - config/routes/*.rb
    - lib/tasks/*.rake
    - lib/devise/**/*.rb
    - app/views/**/*.rb
    - test/factories/*.rb

Performance/MethodObjectAsBlock:
  Exclude:
    - app/queries/**/*.rb

Rails/UnknownEnv:
  Exclude:
    - app/controllers/webhooks/application_controller.rb

Rails/Output:
  Exclude:
    - app/views/**/*.rb